# Tutorial: APEX for AIME (Math)
In this tutorial, we optimize GPT-4.1 Mini's Chain of Thought (`dspy.ChainOfThought`) for solving math problems (AIME) using the `dspy.APEX` optimizer. APEX performs targeted failure/success analyses, synthesizes hypotheses, and keeps the best prompts observed on the calibration set.

<details>
<summary>Recommended: Set up MLflow Autologging to understand what's happening under the hood.</summary>

### MLflow DSPy Integration

<a href="https://mlflow.org/">MLflow</a> is an LLMOps tool that natively integrates with DSPy and offers explainability and experiment tracking. MLflow's autologging capability automatically tracks progress of APEX optimization, as well as visualizes prompts and module executions as traces to understand DSPy's behavior better. You can set up MLflow easily by following the four steps below.

**Visualize module executions as traces**

![MLflow Trace](./mlflow-tracing-gepa-aime.png)

**Automatically track optimization progress and results**

![MLflow Tracking](./mlflow-tracking-gepa-aime-optimization.png)


**Setup MLflow**

1. Install MLflow

```bash
%pip install mlflow>=3.0.0
```

2. Start MLflow UI in a separate terminal
```bash
mlflow ui --port 5000 --backend-store-uri sqlite:///mlruns.db
```

3. Connect the notebook to MLflow
```python
import mlflow

mlflow.set_tracking_uri("http://localhost:5000")
mlflow.set_experiment("DSPy")
```

4. Enable autologging.

```python
mlflow.dspy.autolog(
    # Log the optimization progress
    log_compiles=True,
    # Log the evaluation results
    log_evals=True,
    # Log traces from module executions
    log_traces=True,
)
```

To learn more about the integration, visit [MLflow DSPy Documentation](https://mlflow.org/docs/latest/llms/dspy/index.html) as well.
</details>

In [1]:
import os
import dspy
from dspy.adapters import JSONAdapter
import mlflow

# Set MLflow tracking URI
mlflow.set_tracking_uri("http://localhost:5005")
mlflow.set_experiment("dspy-experiments")

# Configure DSPy with MLflow logging
# dspy.configure(experimental=True)

# Enable autologging for DSPy
mlflow.dspy.autolog()

api_key = 'sk-12345' #input("Enter your OpenAI API key: ")
base_url = "https://nexus-master.lmndstaging.com"
model_prefix = "litellm_proxy"

student_lm = dspy.LM(
    model=f"{model_prefix}/openai/gpt-5-mini",
    api_key=api_key,
    base_url=base_url,
    reasoning_effort="minimal",
    temperature=0.0,
)
analysis_lm = dspy.LM(
    model=f"{model_prefix}/openai/gpt-5",
    api_key=api_key,
    base_url=base_url,
    reasoning_effort="minimal",
    temperature=1.0,
)

# APEX uses JSON adapters by default; exposing them makes customization explicit
analysis_adapter = JSONAdapter()
hypothesis_adapter = JSONAdapter()

n_threads = 50  # notebook thread budget used for evaluation and optimization

dspy.configure(lm=student_lm)
dspy.settings.configure(num_threads=n_threads)

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025/10/14 18:53:23 WARNING mlflow.utils.autologging_utils: MLflow dspy autologging is known to be compatible with 2.5.17 <= dspy, but the installed version is 3.0.4b1. If you encounter errors during autologging, try upgrading / downgrading dspy to a compatible version, or try upgrading MLflow.

### Loading the AIME dataset

The AIME exam consists of 2 problem sets of size 15 for each year. For this tutorial, we will use AIME problem sets from previous years (2022-2024) for optimization (amounting to total 3 years × 2 sets × 15 problems = 90 problems, split equally between train and validation sets), and test the performance on AIME 2025 (2 sets × 15 problems = 30 problems). Since AIME 2025 is a small set, we repeat it 5 times for statistical stability in evaluation.

In [2]:
from datasets import load_dataset
import random


def init_dataset():
    train_split = load_dataset("AI-MO/aimo-validation-aime")['train']
    train_split = [
        dspy.Example({
            "problem": x['problem'],
            "solution": x['solution'],
            "answer": x['answer'],
        }).with_inputs("problem")
        for x in train_split
    ]
    random.Random(0).shuffle(train_split)
    tot_num = len(train_split)

    test_split = load_dataset("MathArena/aime_2025")['train']
    test_split = [
        dspy.Example({
            "problem": x['problem'],
            "answer": x['answer'],
        }).with_inputs("problem")
        for x in test_split
    ]

    train_set = train_split[: int(0.5 * tot_num)]
    val_set = train_split[int(0.5 * tot_num):]
    test_set = test_split * 5

    return train_set, val_set, test_set

In [3]:
train_set, val_set, test_set = init_dataset()

len(train_set), len(val_set), len(test_set)

(45, 45, 150)

Let's view an example task input

In [4]:
print("Problem:")
print(train_set[0]['problem'])
print("\n\nSolution:")
print(train_set[0]['solution'])
print("\n\nAnswer:")
print(train_set[0]['answer'])

Problem:
In isosceles trapezoid $ABCD$, parallel bases $\overline{AB}$ and $\overline{CD}$ have lengths $500$ and $650$, respectively, and $AD=BC=333$. The angle bisectors of $\angle{A}$ and $\angle{D}$ meet at $P$, and the angle bisectors of $\angle{B}$ and $\angle{C}$ meet at $Q$. Find $PQ$.


Solution:
We have the following diagram:

Let $X$ and $W$ be the points where $AP$ and $BQ$ extend to meet $CD$, and $YZ$ be the height of $\triangle AZB$. As proven in Solution 2, triangles $APD$ and $DPW$ are congruent right triangles. Therefore, $AD = DW = 333$. We can apply this logic to triangles $BCQ$ and $XCQ$ as well, giving us $BC = CX = 333$. Since $CD = 650$, $XW = DW + CX - CD = 16$.
Additionally, we can see that $\triangle XZW$ is similar to $\triangle PQZ$ and $\triangle AZB$. We know that $\frac{XW}{AB} = \frac{16}{500}$. So, we can say that the height of the triangle $AZB$ is $500u$ while the height of the triangle $XZW$ is $16u$. After that, we can figure out the distance from $Y$ to $PQ: \frac{500+16}{2} = 258u$ and the height of triangle $PZQ: 500-258 = 242u$.
Finally, since the ratio between the height of $PZQ$ to the height of $AZB$ is $242:500$ and $AB$ is $500$, $PQ = \boxed{242}.$
~Cytronical
Extend line $PQ$ to meet $AD$ at $P'$ and $BC$ at $Q'$. The diagram looks like this:
[asy] /* Made by MRENTHUSIASM */ size(300); pair A, B, C, D, A1, B1, C1, D1, P, Q, P1, Q1; A = (-250,6*sqrt(731)); B = (250,6*sqrt(731)); C = (325,-6*sqrt(731)); D = (-325,-6*sqrt(731)); A1 = bisectorpoint(B,A,D); B1 = bisectorpoint(A,B,C); C1 = bisectorpoint(B,C,D); D1 = bisectorpoint(A,D,C); P = intersectionpoint(A--300*(A1-A)+A,D--300*(D1-D)+D); Q = intersectionpoint(B--300*(B1-B)+B,C--300*(C1-C)+C); P1 = intersectionpoint(A--D,P--(-300)*(Q-P)+P); Q1 = intersectionpoint(B--C,Q--300*(Q-P)+Q); draw(anglemark(P,A,B,1000),red); draw(anglemark(D,A,P,1000),red); draw(anglemark(A,B,Q,1000),red); draw(anglemark(Q,B,C,1000),red); draw(anglemark(P,D,A,1000),red); draw(anglemark(C,D,P,1000),red); draw(anglemark(Q,C,D,1000),red); draw(anglemark(B,C,Q,1000),red); add(pathticks(anglemark(P,A,B,1000), n = 1, r = 0.15, s = 750, red)); add(pathticks(anglemark(D,A,P,1000), n = 1, r = 0.15, s = 750, red)); add(pathticks(anglemark(A,B,Q,1000), n = 1, r = 0.15, s = 750, red)); add(pathticks(anglemark(Q,B,C,1000), n = 1, r = 0.15, s = 750, red)); add(pathticks(anglemark(P,D,A,1000), n = 2, r = 0.12, spacing = 150, s = 750, red)); add(pathticks(anglemark(C,D,P,1000), n = 2, r = 0.12, spacing = 150, s = 750, red)); add(pathticks(anglemark(Q,C,D,1000), n = 2, r = 0.12, spacing = 150, s = 750, red)); add(pathticks(anglemark(B,C,Q,1000), n = 2, r = 0.12, spacing = 150, s = 750, red)); dot("$A$",A,1.5*dir(A),linewidth(4)); dot("$B$",B,1.5*dir(B),linewidth(4)); dot("$C$",C,1.5*dir(C),linewidth(4)); dot("$D$",D,1.5*dir(D),linewidth(4)); dot("$P$",P,1.5*NE,linewidth(4)); dot("$Q$",Q,1.5*NW,linewidth(4)); dot("$P'$",P1,1.5*W,linewidth(4)); dot("$Q'$",Q1,1.5*E,linewidth(4)); draw(A--B--C--D--cycle^^A--P--D^^B--Q--C^^P--Q); draw(P--P1^^Q--Q1,dashed); [/asy]
Because the trapezoid is isosceles, by symmetry $PQ$ is parallel to $AB$ and $CD$. Therefore, $\angle PAB \cong \angle APP'$ by interior angles and $\angle PAB \cong \angle PAD$ by the problem statement. Thus, $\triangle P'AP$ is isosceles with $P'P = P'A$. By symmetry, $P'DP$ is also isosceles, and thus $P'A = \frac{AD}{2}$. Similarly, the same thing is happening on the right side of the trapezoid, and thus $P'Q'$ is the midline of the trapezoid. Then, $PQ = P'Q' - (P'P + Q'Q)$.
Since $P'P = P'A = \frac{AD}{2}, Q'Q = Q'B = \frac{BC}{2}$ and $AD = BC = 333$, we have $P'P + Q'Q = \frac{333}{2} + \frac{333}{2} = 333$. The length of the midline of a trapezoid is the average of their bases, so $P'Q' = \frac{500+650}{2} = 575$. Finally, $PQ = 575 - 333 = \boxed{242}$.
~KingRavi
We have the following diagram:

Extend lines $AP$ and $BQ$ to meet line $DC$ at points $W$ and $X$, respectively, and extend lines $DP$ and $CQ$ to meet $AB$ at points $Z$ and $Y$, respectively.
Claim: quadrilaterals $AZWD$ and $BYXC$ are rhombuses.
Proof: Since $\angle DAB + \angle ADC = 180^{\circ}$, $\angle ADP + \angle PAD = 90^{\circ}$. Therefore, triangles $APD$, $APZ$, $DPW$ and $PZW$ are all right triangles. By SAA congruence, the first three triangles are congruent; by SAS congruence, $\triangle PZW$ is congruent to the other three. Therefore, $AD = DW = WZ = AZ$, so $AZWD$ is a rhombus. By symmetry, $BYXC$ is also a rhombus.
Extend line $PQ$ to meet $\overline{AD}$ and $\overline{BC}$ at $R$ and $S$, respectively. Because of rhombus properties, $RP = QS = \frac{333}{2}$. Also, by rhombus properties, $R$ and $S$ are the midpoints of segments $AD$ and $BC$, respectively; therefore, by trapezoid properties, $RS = \frac{AB + CD}{2} = 575$. Finally, $PQ = RS - RP - QS = \boxed{242}$.
~ihatemath123
Let $X$ and $Y$ be the feet of the altitudes from $P$ and $Q$, respectively, to $AB$, and let $Z$ and $W$ be the feet of the altitudes from $P$ and $Q$, respectively, to $CD$. Side $AB$ is parallel to side $CD$, so $XYWZ$ is a rectangle with width $PQ$. Furthermore, because $CD - AB = 650-500 = 150$ and trapezoid $ABCD$ is isosceles, $WC - YB = ZD - XA = 75$.
Also because $ABCD$ is isosceles, $\angle ABC + \angle BCD$ is half the total sum of angles in $ABCD$, or $180^{\circ}$. Since $BQ$ and $CQ$ bisect $\angle ABC$ and $\angle BCD$, respectively, we have $\angle QBC + \angle QCB = 90^{\circ}$, so $\angle BQC = 90^{\circ}$.
Letting $BQ = 333k$, applying Pythagoras to $\triangle BQC$ yields $QC = 333\sqrt{1-k^2}$. We then proceed using similar triangles: $\angle BYQ = \angle BQC = 90^{\circ}$ and $\angle YBQ = \angle QBC$, so by AA similarity $YB = 333k^2$. Likewise, $\angle CWQ = \angle BQC = 90^{\circ}$ and $\angle WCQ = \angle QCB$, so by AA similarity $WC = 333(1 - k^2)$. Thus $WC + YB = 333$.
Adding our two equations for $WC$ and $YB$ gives $2WC = 75 + 333 = 408$. Therefore, the answer is $PQ = ZW = CD - 2WC = 650 - 408 = \boxed{242}$.
~Orange_Quail_9
This will be my first solution on AoPS. My apologies in advance for any errors.
Angle bisectors can be thought of as the locus of all points equidistant from the lines whose angle they bisect. It can thus be seen that $P$ is equidistant from  $AB, AD,$ and $CD$ and $Q$ is equidistant from  $AB, BC,$ and $CD.$ If we let the feet of the altitudes from $P$ to $AB, AD,$ and $CD$ be called $E, F,$ and $G$ respectively, we can say that $PE = PF = PG.$ Analogously, we let the feet of the altitudes from $Q$ to $AB, BC,$ and $CD$ be $H, I,$ and $J$ respectively. Thus, $QH = QI = QJ.$ Because $ABCD$ is an isosceles trapezoid, we can say that all of the altitudes are equal to each other.
By SA as well as SS congruence for right triangles, we find that triangles $AEP, AFP, BHQ,$ and $BIQ$ are congruent. Similarly, $DFP, DGP, CJQ,$ and $CIQ$ by the same reasoning. Additionally, $EH = GJ = PQ$ since $EHQP$ and $GJQP$ are congruent rectangles.
If we then let $x = AE = AF = BH = BI,$ let $y = CI = CJ = DG = DF,$ and let $z = EH = GJ = PQ,$ we can create the following system of equations with the given side length information:
\begin{align*} 2x + z &= 500, \\ 2y + z &= 650, \\ x + y &= 333. \end{align*}
Adding the first two equations, subtracting by twice the second, and dividing by $2$ yields $z = PQ = \boxed{242}.$
~regular
Extend line $PQ$ to meet $AD$ at $P'$ and $BC$ at $Q'$. The diagram looks like this:
[asy] /* Made by MRENTHUSIASM */ size(300); pair A, B, C, D, A1, B1, C1, D1, P, Q, P1, Q1; A = (-250,6*sqrt(731)); B = (250,6*sqrt(731)); C = (325,-6*sqrt(731)); D = (-325,-6*sqrt(731)); A1 = bisectorpoint(B,A,D); B1 = bisectorpoint(A,B,C); C1 = bisectorpoint(B,C,D); D1 = bisectorpoint(A,D,C); P = intersectionpoint(A--300*(A1-A)+A,D--300*(D1-D)+D); Q = intersectionpoint(B--300*(B1-B)+B,C--300*(C1-C)+C); P1 = intersectionpoint(A--D,P--(-300)*(Q-P)+P); Q1 = intersectionpoint(B--C,Q--300*(Q-P)+Q); draw(anglemark(P,A,B,1000),red); draw(anglemark(D,A,P,1000),red); draw(anglemark(A,B,Q,1000),red); draw(anglemark(Q,B,C,1000),red); draw(anglemark(P,D,A,1000),red); draw(anglemark(C,D,P,1000),red); draw(anglemark(Q,C,D,1000),red); draw(anglemark(B,C,Q,1000),red); add(pathticks(anglemark(P,A,B,1000), n = 1, r = 0.15, s = 750, red)); add(pathticks(anglemark(D,A,P,1000), n = 1, r = 0.15, s = 750, red)); add(pathticks(anglemark(A,B,Q,1000), n = 1, r = 0.15, s = 750, red)); add(pathticks(anglemark(Q,B,C,1000), n = 1, r = 0.15, s = 750, red)); add(pathticks(anglemark(P,D,A,1000), n = 2, r = 0.12, spacing = 150, s = 750, red)); add(pathticks(anglemark(C,D,P,1000), n = 2, r = 0.12, spacing = 150, s = 750, red)); add(pathticks(anglemark(Q,C,D,1000), n = 2, r = 0.12, spacing = 150, s = 750, red)); add(pathticks(anglemark(B,C,Q,1000), n = 2, r = 0.12, spacing = 150, s = 750, red)); dot("$A$",A,1.5*dir(A),linewidth(4)); dot("$B$",B,1.5*dir(B),linewidth(4)); dot("$C$",C,1.5*dir(C),linewidth(4)); dot("$D$",D,1.5*dir(D),linewidth(4)); dot("$P$",P,1.5*NE,linewidth(4)); dot("$Q$",Q,1.5*NW,linewidth(4)); dot("$P'$",P1,1.5*W,linewidth(4)); dot("$Q'$",Q1,1.5*E,linewidth(4)); draw(A--B--C--D--cycle^^A--P--D^^B--Q--C^^P--Q); draw(P--P1^^Q--Q1,dashed); [/asy]
Since $\angle A + \angle D=\angle B + \angle C = 180^{\circ}$, it follows that $\angle P'AP+\angle P'DP = \angle Q'BQ + \angle Q'CQ = 90^{\circ}$. Thus, $\angle APD = \angle BQC = 90^{\circ}$, implying that $\triangle APD$ and $\triangle BQC$ are right triangles. Since $P'P$ and $Q'Q$ are medians, $P'P+Q'Q=\frac{333\times2}{2}=333$. Since $P'Q'=\frac{500+650}{2}=575$, we have $PQ+P'P+Q'Q=575$, or $PQ=575-333=\boxed{242}$.
~sigma
Let $PQ = x$. Note that since $AP$ bisects $\angle{A}$ and $DP$ bisects $\angle{D}$, we have \[\angle{APD} = 180^{\circ}-\tfrac12 \angle{A}-\tfrac12 \angle{D}=90^{\circ}.\] Let $\angle{ADP}=\theta$. We have that $\angle{ADC} = 2\theta.$ Now, drop an altitude from $A$ to $CD$ at $E$. Notice that $DE=\tfrac{650-500}{2}=75$. By the definition of cosine, we have \[\cos{2\theta}=1-2\cos^2{\theta}=\tfrac{75}{333}=\tfrac{25}{111} \implies \cos{\theta}=\tfrac{2\sqrt{1887}}{111}.\] Notice, however, that we can also apply this to $\triangle{APD}$; we have \[\cos{\theta}=\tfrac{DP}{333} \implies DP=6\sqrt{1887}.\] By the Pythagorean Theorem, we get \[AP=\sqrt{333^2-(6\sqrt{1887})^2}=3\sqrt{4773}.\] Then, drop an altitude from $P$ to $AB$ at $F$; if $AF=y$, then $PQ=x=500-2y$. Because $AP$ is an angle bisector, we see that $\angle{BAP}=\angle{DAP}=90^{\circ}-\theta$. Again, by the definition of cosine, we have \[\cos{(90^{\circ}-\theta)}=\sin{\theta}=\tfrac{\sqrt{4773}}{111}=\tfrac{y}{3\sqrt{4773}} \implies y=129.\] Finally, $PQ=500-2y=\boxed{242}$.
~pqr.
As in solution 4, $\angle APD = 90^{\circ}$. Set $k = AX$ and $x = DP$.
We know that $DZ = AX + \frac{DC-AB}{2}$, so $DZ = k + \frac{650-500}{2} = k + 75$.
$\triangle DPZ \sim \triangle APD$ by AA, so we have $\frac{PD}{AD} = \frac{ZD}{PD}$, resulting in
\[\frac{x}{333} = \frac{k+75}{x} \text{ (1)}\]
$\triangle APX \sim \triangle ADP$ by AA, so we have $\frac{AP}{AD} = \frac{AX}{AP}$, resulting in
\[\frac{\sqrt{333^2-x^2}}{333} = \frac{k}{\sqrt{333^2-k^2}} \text{ (2)}\]
From $\text{(1)}$, we have $x^2 = 333k + 333(75) = 333k + 24975$. From $\text{(2)}$, we have $333^2 - x^2 = 333k$, or $x^2 = 333^2 - 333k$. Thus, $333k + 24975 = 333^2 - 333k$. Solving for $k$ yields $k = 129$.
By symmetry, $YB = AX = 129$. Thus, $PQ = XY = AB - 2AX = 500 - 2(129) = \boxed{242}$.
~ adam_zheng


Answer:
242

### Let's define the program: A simple `dspy.ChainOfThought`

In [5]:
class GenerateResponse(dspy.Signature):
    """Solve the problem and provide the answer in the correct format."""
    problem = dspy.InputField()
    answer = dspy.OutputField()


program = dspy.ChainOfThought(GenerateResponse)

### Defining the evaluation metric
We simply check exact match between the predicted answer and the correct answer.

In [6]:
def metric(example, prediction, trace=None, pred_name=None, pred_trace=None):
    correct_answer = int(example['answer'])
    try:
        llm_answer = int(prediction.answer)
    except ValueError:
        return 0
    return int(correct_answer == llm_answer)

### Evaluating unoptimized Chain Of Thought

We evaluate with the thread budget defined above and tolerate up to `len(test_set)` transient errors so the run completes even on constrained proxies. If your provider enforces stricter limits, lower `n_threads` or tighten `max_errors`.

In [7]:
# Removed max_errors configuration since there should be no errors
eval_kwargs = dict(
    num_threads=n_threads,
    display_progress=True,
    display_table=5,
    provide_traceback=False,
)

evaluate = dspy.Evaluate(
    devset=test_set,
    metric=metric,
    **eval_kwargs,
)

baseline_result = evaluate(program)
baseline_result.score

Average Metric: 80.00 / 150 (53.3%): 100%|██████████| 150/150 [00:04<00:00, 34.89it/s]

2025/10/14 18:53:32 INFO dspy.evaluate.evaluate: Average Metric: 80 / 150 (53.3%)

,problem,example_answer,reasoning,pred_answer,metric
0,Find the sum of all integer bases $b>9$ for which $17_b$ is a divi...,70,We interpret 17_b = b+7 and 97_b = 9b+7. We need b+7 to divide 9b+...,70,✔️ [1]
1,"On $\triangle ABC$ points $A, D, E$, and $B$ lie in that order on ...",588,"Set up affine coordinates with A=(0,0), B=(1,0), C=(0,1). Points o...",441,✔️ [0]
2,The 9 members of a baseball team went to an ice-cream parlor after...,16,"We must count assignments of 3 labeled flavors (C, V, S) to 9 dist...",16,✔️ [1]
3,"Find the number of ordered pairs $(x,y)$, where both $x$ and $y$ a...",117,"We need integer solutions (x,y) in [-100,100] satisfying 12x^2 - x...",117,✔️ [1]
4,There are $8!= 40320$ eight-digit positive integers that use each ...,279,Divisibility by 22 means divisible by 2 and 11. Units digit must b...,279,✔️ [1]

53.33

[Trace(trace_id=tr-4cfdcd178635b6f49f180b65cace7270), Trace(trace_id=tr-7b344ddc70882da588fbba9dc42f782b), Trace(trace_id=tr-c8b894808f5a5620f748d0ff66f81dcd), Trace(trace_id=tr-dddf7e09c547d5e9bb4a578a80a80f01), Trace(trace_id=tr-4ed37ad9bb81653c70b0c2898a7b35d7), Trace(trace_id=tr-97f8caffe2295e02ed12a39da56ecbe5), Trace(trace_id=tr-8f00c7abb5392a03d3a6c85d225ebc2a), Trace(trace_id=tr-fe1fbdf9286f8838081e5b1a5c4e0af3), Trace(trace_id=tr-c241d4b65ce7d8b746c52c8fae5cfbbf), Trace(trace_id=tr-a909293e9d5bf0fc5cea6d872a817541)]

### Augmenting the metric for APEX
APEX benefits from feedback about why predictions fail. We extend the metric to provide textual guidance (and optional worked solutions) that the optimizer can feed into its failure and success analyses.

In [8]:
def metric_with_feedback(example, prediction, trace=None, pred_name=None, pred_trace=None):
    correct_answer = int(example['answer'])
    written_solution = example.get('solution', '')
    try:
        llm_answer = int(prediction.answer)
    except ValueError:
        feedback_text = (
            f"The final answer must be a valid integer and nothing else. You responded with '{prediction.answer}', which couldn't be parsed as an integer."
        )
        feedback_text += f" The correct answer is '{correct_answer}'."
        if written_solution:
            feedback_text += (
                f" Here's the full step-by-step solution:\n{written_solution}\n\n"
                "Reflect on this solution and ensure your final answer is a valid integer when you attempt similar problems."
            )
        return dspy.Prediction(score=0, feedback=feedback_text)

    score = int(correct_answer == llm_answer)
    if score == 1:
        feedback_text = f"Your answer is correct. The correct answer is '{correct_answer}'."
    else:
        feedback_text = f"Your answer is incorrect. The correct answer is '{correct_answer}'."

    if written_solution:
        feedback_text += (
            f" Here's the full step-by-step solution:\n{written_solution}\n\n"
            "Use it to identify the mistakes in your reasoning before trying again."
        )

    return dspy.Prediction(score=score, feedback=feedback_text)

### Optimize the program with `dspy.APEX`

APEX runs targeted analyses over failure and success cases, proposes hypotheses with complete prompt updates, and keeps the best candidate on the calibration set. We limit the budget to a few iterations to keep the tutorial runtime manageable. Use `verbosity` to control logging (`"none"`, `"normal"`, or `"high"`) and `num_threads` to parallelize execution.

In [9]:
from dspy.teleprompt.apex_optimizer import APEX

# Fixed configuration for parallel execution with enhanced visibility
optimizer = APEX(
    metric=metric_with_feedback,
    analysis_lm=analysis_lm,        # Required parameter
    hypothesis_lm=analysis_lm,       # Optional, defaults to analysis_lm if not provided
    analysis_adapter=analysis_adapter,
    hypothesis_adapter=hypothesis_adapter,
    max_iterations=1,
    num_hypotheses=1,
    num_eval_runs=1,
    train_sample=20,
    success_threshold=1.0,
    convergence_patience=5,
    num_threads=n_threads,           # Using n_threads=50 from configuration
    verbosity="high",                # Enhanced visibility into the optimization process
    seed=42,
)

optimized_program = optimizer.compile(
    student=program,
    trainset=train_set,
    valset=val_set,
)

2025/10/14 18:53:33 INFO dspy.teleprompt.apex_optimizer: APEX: running with num_threads=50
2025/10/14 18:53:33 INFO dspy.teleprompt.apex_optimizer: APEX: Configuration - max_iterations=1, num_hypotheses=1, success_threshold=1.00, convergence_patience=5
2025/10/14 18:53:33 INFO dspy.teleprompt.apex_optimizer: APEX: Using seed=42 for reproducibility
2025/10/14 18:53:33 INFO dspy.teleprompt.apex_optimizer: APEX: Evaluating initial baseline on validation set

Processed 45 / 45 examples: 100%|██████████| 45/45 [00:00<00:00, 446.91it/s]

2025/10/14 18:53:34 INFO dspy.teleprompt.apex_optimizer: APEX: Initial baseline score=0.5111
2025/10/14 18:53:34 INFO dspy.teleprompt.apex_optimizer: APEX: iteration 1 started (train sample=20, val size=45)
2025/10/14 18:53:34 INFO dspy.teleprompt.apex_optimizer: APEX: Sampled 20 training examples from 45 total

Processed 20 / 20 examples: 100%|██████████| 20/20 [00:00<00:00, 107.57it/s]

2025/10/14 18:53:34 INFO dspy.teleprompt.apex_optimizer: APEX: Train evaluation complete - 6 failures, 14 successes

Processed 1 / 6 examples:  17%|█▋        | 1/6 [00:19<01:35, 19.14s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "ro...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Processed 6 / 6 examples: 100%|██████████| 6/6 [00:22<00:00,  3.79s/it]

2025/10/14 18:53:57 INFO dspy.teleprompt.apex_optimizer: APEX: failure analysis #1 (ambiguous-instruction) → In unknown (Predict), the solver guessed an answer '13' without deriving [(1−x)(1−y)(1−z)]^2 and ignored the trigonometric or algebraic transformations indicated by the system. The metric_feedback shows the correct result is 1/32 leading to m+n=33, while the produced answer was 13.
2025/10/14 18:53:57 INFO dspy.teleprompt.apex_optimizer: APEX: failure analysis #2 (missing-constraint) → In unknown (Predict), the solution counted forbidden pairs incorrectly: it excluded a=6 and any 20 correctly, but subtracted only two special AP pairs (12,21) and (16,28), missing the additional invalid pair (7,9) from the AP 3,5,7,9. Execution flow shows: Actual outputs answer '227' with reasoning subtracting 23+23+2, while the metric feedback specifies three exclusions leading to 231−3=228.
2025/10/14 18:53:57 INFO dspy.teleprompt.apex_optimizer: APEX: failure analysis #3 (wrong-values/content) → In unknown (Predict), the final computed bounded-region count for m=7, n=5 was incorrectly given as 241 instead of the correct 244. The execution_flow shows the predictor concluded F = 247 then subtracted unbounded faces to get 241, while the metric_feedback details the correct formula f(m,n) = C(m,2)C(n,2) + mn − 1 yielding 244.
2025/10/14 18:53:57 INFO dspy.teleprompt.apex_optimizer: APEX: failure analysis #4 (ambiguous-instruction) → In unknown (Predict), the solver assumed every rectangle inscribed in the circumcircle must have opposite vertices antipodal and counted only vertex-vertex rectangles as cyclic rectangles (giving 30). However, the problem asks for rectangles whose sides lie on sides or diagonals of the dodecagon; many such rectangles are formed by intersections of sides/diagonals and are not determined solely by antipodal vertex pairs. Metric feedback shows the correct total is 315 via case analysis of segment slopes.
2025/10/14 18:53:57 INFO dspy.teleprompt.apex_optimizer: APEX: failure analysis #5 (ambiguous-instruction) → In unknown (Predict), the final answer was given as 117 based on an admitted memory guess, contradicting the metric_feedback’s correct answer 033. Execution flow shows only a single predictor handling the full problem; the reasoning ignored the geometric relations (midpoint M on AB via radical axis, AM=6, MP=4) and thus produced the wrong numeric result.
2025/10/14 18:53:57 INFO dspy.teleprompt.apex_optimizer: APEX: failure analysis #6 (wrong-values) → In unknown (Predict), the model produced the final answer '100' for the equilateral hexagon problem, but the metric feedback shows the correct side length is 80. Execution flow indicates only a single predictor handled the problem, and it returned an incorrect numeric result without aligning to the similarity/ratio relations (e.g., BP=3x/2, AR=5x/4) that yield x=80.

Processed 1 / 6 examples:  17%|█▋        | 1/6 [00:17<01:29, 17.97s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "su...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Processed 6 / 6 examples: 100%|██████████| 6/6 [00:30<00:00,  5.04s/it]

2025/10/14 18:54:27 INFO dspy.teleprompt.apex_optimizer: APEX: success analysis #1 (clear-instruction-execution) → The solver mapped the rhombus-diagonal constraints to constant edge length and fixed pairwise dot products, formed the Gram matrix for edge vectors with off-diagonal signs distinguishing the two noncongruent configurations, and computed volume via det(Gram) to obtain a clean ratio (63/62).
2025/10/14 18:54:27 INFO dspy.teleprompt.apex_optimizer: APEX: success analysis #2 (clear-instruction-execution) → The predictor enumerated all semifinal pairings, computed Carl’s conditional win probabilities for each bracket configuration using given match odds, and averaged them, yielding the exact tournament win probability.
2025/10/14 18:54:27 INFO dspy.teleprompt.apex_optimizer: APEX: success analysis #3 (clear-instruction-execution) → The predictor recognized and applied the cubic symmetric identity linking S = sum of pairwise quadratic-linear terms to (a+b+c)^3, converted constraints into symmetric polynomials, and used the 100-shift (x=100−a etc.) to force xyz=0, yielding that one variable equals 100 and enabling clean counting via inclusion–exclusion.
2025/10/14 18:54:27 INFO dspy.teleprompt.apex_optimizer: APEX: success analysis #4 (clear-instruction-execution) → The solver reframed the base-8 palindrome as a 4-digit ABBA_8 form and derived its decimal value formula (513A + 72B) to enumerate candidates under 1000, selecting the largest that is also a base-10 palindrome.
2025/10/14 18:54:27 INFO dspy.teleprompt.apex_optimizer: APEX: success analysis #5 (clear-instruction-execution) → The predictor maximized x_{76} and minimized x_{16} by concentrating all positive mass on indices 76–100 and all negative mass on indices 1–16, using the constraints |sum|=1 and sum=0 with monotonicity to derive a=1/50 and b=−1/32.
2025/10/14 18:54:27 INFO dspy.teleprompt.apex_optimizer: APEX: success analysis #6 (clear-instruction-execution) → A single predictor computed PQ by leveraging symmetry and angle-bisector properties in an isosceles trapezoid, reducing the geometry to a simple invariant (midline minus symmetric offsets) to yield 242.
2025/10/14 18:54:27 INFO dspy.teleprompt.apex_optimizer: APEX: iteration 1 analyzed 6 failure(s) and 6 success(es)
2025/10/14 18:54:27 INFO dspy.teleprompt.apex_optimizer: APEX: Generating up to 1 hypotheses from 6 failures

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "hy...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
2025/10/14 18:54:49 INFO dspy.teleprompt.apex_optimizer: APEX: hypothesis #1 (Introduce a strict, lightweight solution protocol for the single predictor: enforce variable/constraint declaration, derivation-first computation, formula citation, and a mandatory final sanity check. Require a deterministic answer format (single integer or simplified rational) and forbid guessing. This aligns with successful patterns that built Gram matrices, symmetric identities, and enumerations before answering.) targeting Ambiguous instruction leading to guessing without derivation, Missing explicit constraints and validation checks before final answer, Lack of required step-by-step algebraic or combinatorial computation, No final consistency check against problem conditions, Failure to state and use variable definitions and known formulas [impact=0.82, generalizability=0.86]
2025/10/14 18:54:49 INFO dspy.teleprompt.apex_optimizer:   → predict: You are a competition math solver. Solve the problem rigorously and return only the final numeric answer in the required format. Do not guess. Always derive and verify.

Solution protocol (follow all ...
2025/10/14 18:54:49 INFO dspy.teleprompt.apex_optimizer:      Rationale: The dominant failures stem from ambiguous instructions enabling guesses and skipped derivations, and from missing constraints in counting/geometry problems. The successful cases all followed a disciplined approach: formalizing constraints, citing formulas (Gram determinant, symmetric identities), enumerating cases, and computing exactly. This prompt adds a minimal but strict protocol to force those successful behaviors without changing domain knowledge. It also enforces exact final formatting and a sanity check, which should catch miscounts (e.g., missing an invalid pair) and wrong formula applications.
2025/10/14 18:54:49 INFO dspy.teleprompt.apex_optimizer: APEX: iteration 1 produced 1 hypothesis(es)
2025/10/14 18:54:49 INFO dspy.teleprompt.apex_optimizer: APEX: hypothesis #1 - strategy: Introduce a strict, lightweight solution protocol for the single predictor: enforce variable/constraint declaration, derivation-first computation, formula citation, and a mandatory final sanity check. Require a deterministic answer format (single integer or simplified rational) and forbid guessing. This aligns with successful patterns that built Gram matrices, symmetric identities, and enumerations before answering., impact: 0.82, updating: predict
2025/10/14 18:54:49 INFO dspy.teleprompt.apex_optimizer: APEX: Detailed hypothesis info follows...

Processed 45 / 45 examples: 100%|██████████| 45/45 [00:00<00:00, 1043.11it/s]

2025/10/14 18:54:49 INFO dspy.teleprompt.apex_optimizer: APEX: iteration 1 baseline score=0.5111

Processed 1 / 45 examples:   2%|▏         | 1/45 [00:10<07:57, 10.86s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Processed 3 / 45 examples:   7%|▋         | 3/45 [00:15<02:49,  4.04s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Processed 6 / 45 examples:  13%|█▎        | 6/45 [00:22<01:41,  2.60s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## an...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Processed 23 / 45 examples:  51%|█████     | 23/45 [00:57<01:15,  3.43s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Processed 45 / 45 examples: : 47it [03:52,  4.95s/it]

2025/10/14 18:58:41 INFO dspy.teleprompt.apex_optimizer: APEX: iteration 1 hypothesis score=0.6444
2025/10/14 18:58:41 INFO dspy.teleprompt.apex_optimizer: APEX: hypothesis details → {'observation': 'Failures cluster around the single predictor making premature guesses, misreading constraints, and outputting wrong numeric values due to skipped derivations and missing explicit problem-structure steps. Successes show that when the solver explicitly models constraints, builds formulas, and computes step-by-step, results are correct.', 'fixable_root_causes': ['Ambiguous instruction leading to guessing without derivation', 'Missing explicit constraints and validation checks before final answer', 'Lack of required step-by-step algebraic or combinatorial computation', 'No final consistency check against problem conditions', 'Failure to state and use variable definitions and known formulas'], 'non_fixable_root_causes': [], 'impact_score': 0.82, 'generalizability_score': 0.86, 'strategy': 'Introduce a strict, lightweight solution protocol for the single predictor: enforce variable/constraint declaration, derivation-first computation, formula citation, and a mandatory final sanity check. Require a deterministic answer format (single integer or simplified rational) and forbid guessing. This aligns with successful patterns that built Gram matrices, symmetric identities, and enumerations before answering.', 'expected_impact': 'Reduce wrong-values and ambiguous-instruction errors by 25–40% on validation by preventing guess-based outputs and enforcing derivation and checks; specifically, should fix cases like miscounted exclusions, incorrect region-count formulas, and wrong geometric lengths by requiring formula-based computation and a final constraint verification.', 'prompt_changes': {'predict': {'new_prompt': 'You are a competition math solver. Solve the problem rigorously and return only the final numeric answer in the required format. Do not guess. Always derive and verify.\n\nSolution protocol (follow all steps):\n1) Parse and restate: Identify what is asked (target quantity) and list given constraints and definitions. Introduce variables with clear meanings.\n2) Plan: Choose a method suited to the domain (algebraic identities, combinatorics counting with inclusion–exclusion, geometry with similarity/ratios, graph/region formulas, etc.). Cite any standard formula you will use (e.g., C(n,2)C(m,2)+mn−1 for bounded regions formed by m vertical and n horizontal lines; palindrome structure; symmetric polynomial identities; Gram matrix determinant for volumes).\n3) Derive: Execute the plan step-by-step. Show key intermediate expressions (not verbose prose). Carry out necessary case analyses fully when counting. For geometry, set up ratios or coordinates; for counting, enumerate cases and subtract forbidden pairs explicitly.\n4) Sanity check: Verify the result against all constraints (units, parity, bounds, small cases, or plugging into the stated formula). If a discrepancy appears, correct it before finalizing.\n5) Finalize: Output only the final answer in the exact expected numeric format:\n   - An integer if the answer is integral\n   - A reduced fraction a/b with gcd(a,b)=1 for rationals\n   No labels, no extra text, no leading zeros (except 0), and no formatting other than the number itself.\n\nStrict rules:\n- No guessing or recalling from memory without derivation.\n- Do not skip transformations indicated by the problem (e.g., expanding or simplifying expressions like [(1−x)(1−y)(1−z)]^2 when relevant).\n- When subtracting exclusions or counting special cases, list them and justify each subtraction.\n- Keep arithmetic exact; avoid decimal approximations unless exact form is terminating and required.\n\nNow solve the given problem following the protocol. Provide only the final number on the last line.', 'rationale': 'The dominant failures stem from ambiguous instructions enabling guesses and skipped derivations, and from missing constraints in counting/geometry problems. The successful cases all followed a disciplined approach: formalizing constraints, citing formulas (Gram determinant, symmetric identities), enumerating cases, and computing exactly. This prompt adds a minimal but strict protocol to force those successful behaviors without changing domain knowledge. It also enforces exact final formatting and a sanity check, which should catch miscounts (e.g., missing an invalid pair) and wrong formula applications.', 'change_magnitude': <ChangeMagnitude.MINIMAL: 'minimal'>}}}
2025/10/14 18:58:41 INFO dspy.teleprompt.apex_optimizer: APEX: New best candidate found with score 0.6444
2025/10/14 18:58:41 INFO dspy.teleprompt.apex_optimizer: APEX: Improved 1 predictor prompt(s) - strategy: Introduce a strict, lightweight solution protocol for the single predictor: enforce variable/constraint declaration, derivation-first computation, formula citation, and a mandatory final sanity check. Require a deterministic answer format (single integer or simplified rational) and forbid guessing. This aligns with successful patterns that built Gram matrices, symmetric identities, and enumerations before answering.
2025/10/14 18:58:41 INFO dspy.teleprompt.apex_optimizer: APEX: Detailed improved prompts:
2025/10/14 18:58:41 INFO dspy.teleprompt.apex_optimizer:   → predict: You are a competition math solver. Solve the problem rigorously and return only the final numeric answer in the required format. Do not guess. Always derive and verify.

Solution protocol (follow all steps):
1) Parse and restate: Identify what is asked (target quantity) and list given constraints an...
2025/10/14 18:58:41 INFO dspy.teleprompt.apex_optimizer: APEX: iteration 1 best score=0.6444
2025/10/14 18:58:41 INFO dspy.teleprompt.apex_optimizer: APEX: Score improvements from baseline: [0.13333333333333341]
2025/10/14 18:58:41 INFO dspy.teleprompt.apex_optimizer: APEX: Updating program with hypothesis improvements
2025/10/14 18:58:41 INFO dspy.teleprompt.apex_optimizer: APEX: Stopping due to max iterations reached
2025/10/14 18:58:41 INFO dspy.teleprompt.apex_optimizer: APEX: Optimization complete - stopped after 1 iterations (max_iterations)
2025/10/14 18:58:41 INFO dspy.teleprompt.apex_optimizer: APEX: Final score: 0.6444 (initial baseline: 0.5111)
2025/10/14 18:58:41 INFO dspy.teleprompt.apex_optimizer: APEX: Summary - evaluated 2 candidates from 1 hypotheses
2025/10/14 18:58:41 INFO dspy.teleprompt.apex_optimizer: APEX: Best score trajectory across iterations: [0.6444444444444445]

### Inspect the APEX-optimized prompt

In [10]:
print(optimized_program.predict.signature.instructions)

You are a competition math solver. Solve the problem rigorously and return only the final numeric answer in the required format. Do not guess. Always derive and verify.

Solution protocol (follow all steps):
1) Parse and restate: Identify what is asked (target quantity) and list given constraints and definitions. Introduce variables with clear meanings.
2) Plan: Choose a method suited to the domain (algebraic identities, combinatorics counting with inclusion–exclusion, geometry with similarity/ratios, graph/region formulas, etc.). Cite any standard formula you will use (e.g., C(n,2)C(m,2)+mn−1 for bounded regions formed by m vertical and n horizontal lines; palindrome structure; symmetric polynomial identities; Gram matrix determinant for volumes).
3) Derive: Execute the plan step-by-step. Show key intermediate expressions (not verbose prose). Carry out necessary case analyses fully when counting. For geometry, set up ratios or coordinates; for counting, enumerate cases and subtract forbidden pairs explicitly.
4) Sanity check: Verify the result against all constraints (units, parity, bounds, small cases, or plugging into the stated formula). If a discrepancy appears, correct it before finalizing.
5) Finalize: Output only the final answer in the exact expected numeric format:
   - An integer if the answer is integral
   - A reduced fraction a/b with gcd(a,b)=1 for rationals
   No labels, no extra text, no leading zeros (except 0), and no formatting other than the number itself.

Strict rules:
- No guessing or recalling from memory without derivation.
- Do not skip transformations indicated by the problem (e.g., expanding or simplifying expressions like [(1−x)(1−y)(1−z)]^2 when relevant).
- When subtracting exclusions or counting special cases, list them and justify each subtraction.
- Keep arithmetic exact; avoid decimal approximations unless exact form is terminating and required.

Now solve the given problem following the protocol. Provide only the final number on the last line.

Trace(trace_id=tr-57aa38477256d5ebe6a26dceabc057b7)

### Evaluating the Chain Of Thought optimized with APEX

In [11]:
evaluate(optimized_program)

Average Metric: 2.00 / 2 (100.0%):   1%|          | 1/150 [00:12<29:41, 11.96s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 3.00 / 3 (100.0%):   2%|▏         | 3/150 [00:13<08:41,  3.55s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 4.00 / 4 (100.0%):   3%|▎         | 4/150 [00:15<07:46,  3.20s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 5.00 / 5 (100.0%):   3%|▎         | 5/150 [00:17<06:48,  2.82s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 7.00 / 7 (100.0%):   4%|▍         | 6/150 [00:18<04:50,  2.02s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 8.00 / 8 (100.0%):   5%|▌         | 8/150 [00:18<02:39,  1.12s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 9.00 / 9 (100.0%):   6%|▌         | 9/150 [00:19<02:27,  1.05s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## an...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## an...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 10.00 / 10 (100.0%):   7%|▋         | 10/150 [00:21<02:56,  1.26s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 12.00 / 13 (92.3%):   8%|▊         | 12/150 [00:21<02:14,  1.02it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 14.00 / 15 (93.3%):  10%|█         | 15/150 [00:24<02:09,  1.04it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## an...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 16.00 / 17 (94.1%):  11%|█         | 16/150 [00:25<02:25,  1.09s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 17.00 / 18 (94.4%):  12%|█▏        | 18/150 [00:26<01:33,  1.41it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## an...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 18.00 / 19 (94.7%):  13%|█▎        | 19/150 [00:29<03:06,  1.42s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 19.00 / 20 (95.0%):  13%|█▎        | 20/150 [00:31<03:04,  1.42s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 19.00 / 21 (90.5%):  14%|█▍        | 21/150 [00:35<04:21,  2.02s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 20.00 / 22 (90.9%):  15%|█▍        | 22/150 [00:38<04:46,  2.24s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 21.00 / 24 (87.5%):  15%|█▌        | 23/150 [00:38<03:45,  1.78s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 22.00 / 25 (88.0%):  17%|█▋        | 25/150 [00:40<02:47,  1.34s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 27.00 / 30 (90.0%):  20%|██        | 30/150 [00:40<00:56,  2.13it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 28.00 / 32 (87.5%):  21%|██▏       | 32/150 [00:40<00:44,  2.64it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 31.00 / 36 (86.1%):  23%|██▎       | 35/150 [00:43<01:09,  1.66it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 33.00 / 39 (84.6%):  26%|██▌       | 39/150 [00:43<00:35,  3.12it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 34.00 / 40 (85.0%):  26%|██▌       | 39/150 [00:44<00:35,  3.12it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 38.00 / 44 (86.4%):  29%|██▉       | 44/150 [00:44<00:26,  3.98it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 43.00 / 49 (87.8%):  33%|███▎      | 49/150 [00:45<00:26,  3.86it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 44.00 / 50 (88.0%):  33%|███▎      | 49/150 [00:46<00:26,  3.86it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 45.00 / 51 (88.2%):  34%|███▍      | 51/150 [00:47<00:40,  2.42it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 46.00 / 56 (82.1%):  37%|███▋      | 55/150 [00:48<00:24,  3.84it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 50.00 / 60 (83.3%):  39%|███▉      | 59/150 [00:48<00:14,  6.15it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 53.00 / 65 (81.5%):  43%|████▎     | 64/150 [00:52<00:49,  1.72it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## an...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 60.00 / 73 (82.2%):  48%|████▊     | 72/150 [00:53<00:19,  4.02it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 67.00 / 83 (80.7%):  55%|█████▌    | 83/150 [00:54<00:10,  6.25it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 69.00 / 89 (77.5%):  59%|█████▉    | 89/150 [00:54<00:06,  9.43it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 73.00 / 95 (76.8%):  63%|██████▎   | 94/150 [00:56<00:15,  3.64it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 77.00 / 100 (77.0%):  66%|██████▌   | 99/150 [00:58<00:18,  2.83it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 81.00 / 105 (77.1%):  70%|███████   | 105/150 [01:01<00:17,  2.53it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 82.00 / 106 (77.4%):  70%|███████   | 105/150 [01:01<00:17,  2.53it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 83.00 / 107 (77.6%):  71%|███████▏  | 107/150 [01:08<00:45,  1.06s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 83.00 / 108 (76.9%):  71%|███████▏  | 107/150 [01:09<00:45,  1.06s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## an...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 84.00 / 109 (77.1%):  73%|███████▎  | 109/150 [01:12<00:52,  1.27s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 85.00 / 110 (77.3%):  73%|███████▎  | 110/150 [01:15<01:05,  1.64s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 86.00 / 111 (77.5%):  74%|███████▍  | 111/150 [01:18<01:13,  1.90s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 87.00 / 113 (77.0%):  75%|███████▌  | 113/150 [01:23<01:16,  2.07s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 88.00 / 114 (77.2%):  76%|███████▌  | 114/150 [01:29<01:50,  3.08s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 88.00 / 115 (76.5%):  77%|███████▋  | 115/150 [01:32<01:45,  3.01s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 89.00 / 116 (76.7%):  77%|███████▋  | 116/150 [01:35<01:44,  3.07s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 89.00 / 117 (76.1%):  78%|███████▊  | 117/150 [01:36<01:18,  2.36s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 89.00 / 118 (75.4%):  79%|███████▊  | 118/150 [01:36<00:56,  1.75s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 90.00 / 120 (75.0%):  80%|████████  | 120/150 [01:36<00:28,  1.05it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 91.00 / 121 (75.2%):  81%|████████  | 121/150 [01:38<00:37,  1.30s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 91.00 / 122 (74.6%):  81%|████████▏ | 122/150 [01:38<00:27,  1.02it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 91.00 / 124 (73.4%):  82%|████████▏ | 123/150 [01:39<00:26,  1.04it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## an...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 91.00 / 125 (72.8%):  83%|████████▎ | 125/150 [01:41<00:22,  1.09it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 91.00 / 126 (72.2%):  84%|████████▍ | 126/150 [01:41<00:18,  1.30it/s]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 92.00 / 127 (72.4%):  85%|████████▍ | 127/150 [01:43<00:24,  1.05s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 92.00 / 129 (71.3%):  85%|████████▌ | 128/150 [01:45<00:24,  1.10s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 92.00 / 131 (70.2%):  87%|████████▋ | 130/150 [01:48<00:29,  1.49s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 93.00 / 132 (70.5%):  88%|████████▊ | 132/150 [01:50<00:23,  1.31s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 94.00 / 133 (70.7%):  89%|████████▊ | 133/150 [01:53<00:25,  1.52s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 94.00 / 134 (70.1%):  89%|████████▉ | 134/150 [01:53<00:21,  1.32s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 95.00 / 135 (70.4%):  90%|█████████ | 135/150 [01:55<00:20,  1.37s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 95.00 / 136 (69.9%):  91%|█████████ | 136/150 [01:59<00:28,  2.00s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 95.00 / 139 (68.3%):  92%|█████████▏| 138/150 [02:02<00:28,  2.35s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 95.00 / 140 (67.9%):  93%|█████████▎| 140/150 [02:07<00:19,  1.97s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 95.00 / 142 (66.9%):  94%|█████████▍| 141/150 [02:10<00:20,  2.23s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 95.00 / 143 (66.4%):  95%|█████████▌| 143/150 [02:16<00:16,  2.42s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 95.00 / 144 (66.0%):  96%|█████████▌| 144/150 [02:31<00:30,  5.16s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 95.00 / 145 (65.5%):  97%|█████████▋| 145/150 [02:40<00:30,  6.06s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 95.00 / 146 (65.1%):  97%|█████████▋| 146/150 [02:47<00:25,  6.30s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Average Metric: 95.00 / 150 (63.3%): 100%|██████████| 150/150 [02:55<00:00,  1.17s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
2025/10/14 19:02:15 INFO dspy.evaluate.evaluate: Average Metric: 95 / 150 (63.3%)

,problem,example_answer,reasoning,pred_answer,metric
0,Find the sum of all integer bases $b>9$ for which $17_b$ is a divi...,70,1) Parse and restate: - We are asked to find sum of all integer ba...,70,✔️ [1]
1,"On $\triangle ABC$ points $A, D, E$, and $B$ lie in that order on ...",588,"1) Parse and restate: - Triangle ABC with A--D--E--B on AB, length...",588,✔️ [1]
2,The 9 members of a baseball team went to an ice-cream parlor after...,16,1) Parse and restate: - There are 9 distinct players. Each chooses...,16,✔️ [1]
3,"Find the number of ordered pairs $(x,y)$, where both $x$ and $y$ a...",117,1) Parse and restate: We seek the number of ordered integer pairs ...,117,✔️ [1]
4,There are $8!= 40320$ eight-digit positive integers that use each ...,279,1) Parse and restate: - We consider all 8-digit permutations of di...,279,✔️ [1]

EvaluationResult(score=63.33, results=<list of 150 results>)

[Trace(trace_id=tr-e5deda72a41355e90ecc9e1cb4e25945), Trace(trace_id=tr-37602be62283376eae2bed90de62be84), Trace(trace_id=tr-69064799399fe1770be869aa7dccc5ee), Trace(trace_id=tr-9bff023b3bace4f86ac58a92719438af), Trace(trace_id=tr-f3d6a61869d2e9a3bac9a3c5be4567f4), Trace(trace_id=tr-0c8dc903cae334d9e91f49e807ede1b9), Trace(trace_id=tr-9e5a3db66202956731613ab76d20ced7), Trace(trace_id=tr-47903ef023a54336f3538c245f13a7aa), Trace(trace_id=tr-b810af6fde8f5d94276f5bd62fdc1ec2), Trace(trace_id=tr-747d4d0db8a675e142db7b9bdb0e6588)]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

APEX typically improves the GPT-4.1 Mini's performance on AIME 2025 by leveraging targeted analyses while keeping the overall evaluation flow identical to the GEPA tutorial.