# Tutorial: APEX for AIME (Math)
In this tutorial, we optimize GPT-4.1 Mini's Chain of Thought (`dspy.ChainOfThought`) for solving math problems (AIME) using the `dspy.APEX` optimizer. APEX performs targeted failure/success analyses, synthesizes hypotheses, and keeps the best prompts observed on the calibration set.

<details>
<summary>Recommended: Set up MLflow Autologging to understand what's happening under the hood.</summary>

### MLflow DSPy Integration

<a href="https://mlflow.org/">MLflow</a> is an LLMOps tool that natively integrates with DSPy and offers explainability and experiment tracking. MLflow's autologging capability automatically tracks progress of APEX optimization, as well as visualizes prompts and module executions as traces to understand DSPy's behavior better. You can set up MLflow easily by following the four steps below.

**Visualize module executions as traces**

![MLflow Trace](./mlflow-tracing-gepa-aime.png)

**Automatically track optimization progress and results**

![MLflow Tracking](./mlflow-tracking-gepa-aime-optimization.png)


**Setup MLflow**

1. Install MLflow

```bash
%pip install mlflow>=3.0.0
```

2. Start MLflow UI in a separate terminal
```bash
mlflow ui --port 5000 --backend-store-uri sqlite:///mlruns.db
```

3. Connect the notebook to MLflow
```python
import mlflow

mlflow.set_tracking_uri("http://localhost:5000")
mlflow.set_experiment("DSPy")
```

4. Enable autologging.

```python
mlflow.dspy.autolog(
    # Log the optimization progress
    log_compiles=True,
    # Log the evaluation results
    log_evals=True,
    # Log traces from module executions
    log_traces=True,
)
```

To learn more about the integration, visit [MLflow DSPy Documentation](https://mlflow.org/docs/latest/llms/dspy/index.html) as well.
</details>

In [23]:
import os
import dspy
from dspy.adapters import JSONAdapter
import mlflow

# Set MLflow tracking URI
mlflow.set_tracking_uri("http://localhost:5005")
mlflow.set_experiment("dspy-experiments")

# Configure DSPy with MLflow logging
# dspy.configure(experimental=True)

# Enable autologging for DSPy
mlflow.dspy.autolog()

api_key = 'sk-12345' #input("Enter your OpenAI API key: ")
base_url = "https://nexus-master.lmndstaging.com"
model_prefix = "litellm_proxy"

student_lm = dspy.LM(
    model=f"{model_prefix}/openai/gpt-5-mini",
    api_key=api_key,
    base_url=base_url,
    reasoning_effort="minimal",
    temperature=0.0,
)
analysis_lm = dspy.LM(
    model=f"{model_prefix}/openai/gpt-5",
    api_key=api_key,
    base_url=base_url,
    reasoning_effort="minimal",
    temperature=1.0,
)

# APEX uses JSON adapters by default; exposing them makes customization explicit
analysis_adapter = JSONAdapter()
hypothesis_adapter = JSONAdapter()

n_threads = 50  # notebook thread budget used for evaluation and optimization

dspy.configure(lm=student_lm)
dspy.settings.configure(num_threads=n_threads)

2025/10/14 01:10:57 WARNING mlflow.utils.autologging_utils: MLflow dspy autologging is known to be compatible with 2.5.17 <= dspy, but the installed version is 3.0.4b1. If you encounter errors during autologging, try upgrading / downgrading dspy to a compatible version, or try upgrading MLflow.

### Loading the AIME dataset

The AIME exam consists of 2 problem sets of size 15 for each year. For this tutorial, we will use AIME problem sets from previous years (2022-2024) for optimization (amounting to total 3 years × 2 sets × 15 problems = 90 problems, split equally between train and validation sets), and test the performance on AIME 2025 (2 sets × 15 problems = 30 problems). Since AIME 2025 is a small set, we repeat it 5 times for statistical stability in evaluation.

In [24]:
from datasets import load_dataset
import random


def init_dataset():
    train_split = load_dataset("AI-MO/aimo-validation-aime")['train']
    train_split = [
        dspy.Example({
            "problem": x['problem'],
            "solution": x['solution'],
            "answer": x['answer'],
        }).with_inputs("problem")
        for x in train_split
    ]
    random.Random(0).shuffle(train_split)
    tot_num = len(train_split)

    test_split = load_dataset("MathArena/aime_2025")['train']
    test_split = [
        dspy.Example({
            "problem": x['problem'],
            "answer": x['answer'],
        }).with_inputs("problem")
        for x in test_split
    ]

    train_set = train_split[: int(0.5 * tot_num)]
    val_set = train_split[int(0.5 * tot_num):]
    test_set = test_split * 5

    return train_set, val_set, test_set

In [25]:
train_set, val_set, test_set = init_dataset()

len(train_set), len(val_set), len(test_set)

(45, 45, 150)

Let's view an example task input

In [26]:
print("Problem:")
print(train_set[0]['problem'])
print("\n\nSolution:")
print(train_set[0]['solution'])
print("\n\nAnswer:")
print(train_set[0]['answer'])

Problem:
In isosceles trapezoid $ABCD$, parallel bases $\overline{AB}$ and $\overline{CD}$ have lengths $500$ and $650$, respectively, and $AD=BC=333$. The angle bisectors of $\angle{A}$ and $\angle{D}$ meet at $P$, and the angle bisectors of $\angle{B}$ and $\angle{C}$ meet at $Q$. Find $PQ$.


Solution:
We have the following diagram:

Let $X$ and $W$ be the points where $AP$ and $BQ$ extend to meet $CD$, and $YZ$ be the height of $\triangle AZB$. As proven in Solution 2, triangles $APD$ and $DPW$ are congruent right triangles. Therefore, $AD = DW = 333$. We can apply this logic to triangles $BCQ$ and $XCQ$ as well, giving us $BC = CX = 333$. Since $CD = 650$, $XW = DW + CX - CD = 16$.
Additionally, we can see that $\triangle XZW$ is similar to $\triangle PQZ$ and $\triangle AZB$. We know that $\frac{XW}{AB} = \frac{16}{500}$. So, we can say that the height of the triangle $AZB$ is $500u$ while the height of the triangle $XZW$ is $16u$. After that, we can figure out the distance from $Y$ to $PQ: \frac{500+16}{2} = 258u$ and the height of triangle $PZQ: 500-258 = 242u$.
Finally, since the ratio between the height of $PZQ$ to the height of $AZB$ is $242:500$ and $AB$ is $500$, $PQ = \boxed{242}.$
~Cytronical
Extend line $PQ$ to meet $AD$ at $P'$ and $BC$ at $Q'$. The diagram looks like this:
[asy] /* Made by MRENTHUSIASM */ size(300); pair A, B, C, D, A1, B1, C1, D1, P, Q, P1, Q1; A = (-250,6*sqrt(731)); B = (250,6*sqrt(731)); C = (325,-6*sqrt(731)); D = (-325,-6*sqrt(731)); A1 = bisectorpoint(B,A,D); B1 = bisectorpoint(A,B,C); C1 = bisectorpoint(B,C,D); D1 = bisectorpoint(A,D,C); P = intersectionpoint(A--300*(A1-A)+A,D--300*(D1-D)+D); Q = intersectionpoint(B--300*(B1-B)+B,C--300*(C1-C)+C); P1 = intersectionpoint(A--D,P--(-300)*(Q-P)+P); Q1 = intersectionpoint(B--C,Q--300*(Q-P)+Q); draw(anglemark(P,A,B,1000),red); draw(anglemark(D,A,P,1000),red); draw(anglemark(A,B,Q,1000),red); draw(anglemark(Q,B,C,1000),red); draw(anglemark(P,D,A,1000),red); draw(anglemark(C,D,P,1000),red); draw(anglemark(Q,C,D,1000),red); draw(anglemark(B,C,Q,1000),red); add(pathticks(anglemark(P,A,B,1000), n = 1, r = 0.15, s = 750, red)); add(pathticks(anglemark(D,A,P,1000), n = 1, r = 0.15, s = 750, red)); add(pathticks(anglemark(A,B,Q,1000), n = 1, r = 0.15, s = 750, red)); add(pathticks(anglemark(Q,B,C,1000), n = 1, r = 0.15, s = 750, red)); add(pathticks(anglemark(P,D,A,1000), n = 2, r = 0.12, spacing = 150, s = 750, red)); add(pathticks(anglemark(C,D,P,1000), n = 2, r = 0.12, spacing = 150, s = 750, red)); add(pathticks(anglemark(Q,C,D,1000), n = 2, r = 0.12, spacing = 150, s = 750, red)); add(pathticks(anglemark(B,C,Q,1000), n = 2, r = 0.12, spacing = 150, s = 750, red)); dot("$A$",A,1.5*dir(A),linewidth(4)); dot("$B$",B,1.5*dir(B),linewidth(4)); dot("$C$",C,1.5*dir(C),linewidth(4)); dot("$D$",D,1.5*dir(D),linewidth(4)); dot("$P$",P,1.5*NE,linewidth(4)); dot("$Q$",Q,1.5*NW,linewidth(4)); dot("$P'$",P1,1.5*W,linewidth(4)); dot("$Q'$",Q1,1.5*E,linewidth(4)); draw(A--B--C--D--cycle^^A--P--D^^B--Q--C^^P--Q); draw(P--P1^^Q--Q1,dashed); [/asy]
Because the trapezoid is isosceles, by symmetry $PQ$ is parallel to $AB$ and $CD$. Therefore, $\angle PAB \cong \angle APP'$ by interior angles and $\angle PAB \cong \angle PAD$ by the problem statement. Thus, $\triangle P'AP$ is isosceles with $P'P = P'A$. By symmetry, $P'DP$ is also isosceles, and thus $P'A = \frac{AD}{2}$. Similarly, the same thing is happening on the right side of the trapezoid, and thus $P'Q'$ is the midline of the trapezoid. Then, $PQ = P'Q' - (P'P + Q'Q)$.
Since $P'P = P'A = \frac{AD}{2}, Q'Q = Q'B = \frac{BC}{2}$ and $AD = BC = 333$, we have $P'P + Q'Q = \frac{333}{2} + \frac{333}{2} = 333$. The length of the midline of a trapezoid is the average of their bases, so $P'Q' = \frac{500+650}{2} = 575$. Finally, $PQ = 575 - 333 = \boxed{242}$.
~KingRavi
We have the following diagram:

Extend lines $AP$ and $BQ$ to meet line $DC$ at points $W$ and $X$, respectively, and extend lines $DP$ and $CQ$ to meet $AB$ at points $Z$ and $Y$, respectively.
Claim: quadrilaterals $AZWD$ and $BYXC$ are rhombuses.
Proof: Since $\angle DAB + \angle ADC = 180^{\circ}$, $\angle ADP + \angle PAD = 90^{\circ}$. Therefore, triangles $APD$, $APZ$, $DPW$ and $PZW$ are all right triangles. By SAA congruence, the first three triangles are congruent; by SAS congruence, $\triangle PZW$ is congruent to the other three. Therefore, $AD = DW = WZ = AZ$, so $AZWD$ is a rhombus. By symmetry, $BYXC$ is also a rhombus.
Extend line $PQ$ to meet $\overline{AD}$ and $\overline{BC}$ at $R$ and $S$, respectively. Because of rhombus properties, $RP = QS = \frac{333}{2}$. Also, by rhombus properties, $R$ and $S$ are the midpoints of segments $AD$ and $BC$, respectively; therefore, by trapezoid properties, $RS = \frac{AB + CD}{2} = 575$. Finally, $PQ = RS - RP - QS = \boxed{242}$.
~ihatemath123
Let $X$ and $Y$ be the feet of the altitudes from $P$ and $Q$, respectively, to $AB$, and let $Z$ and $W$ be the feet of the altitudes from $P$ and $Q$, respectively, to $CD$. Side $AB$ is parallel to side $CD$, so $XYWZ$ is a rectangle with width $PQ$. Furthermore, because $CD - AB = 650-500 = 150$ and trapezoid $ABCD$ is isosceles, $WC - YB = ZD - XA = 75$.
Also because $ABCD$ is isosceles, $\angle ABC + \angle BCD$ is half the total sum of angles in $ABCD$, or $180^{\circ}$. Since $BQ$ and $CQ$ bisect $\angle ABC$ and $\angle BCD$, respectively, we have $\angle QBC + \angle QCB = 90^{\circ}$, so $\angle BQC = 90^{\circ}$.
Letting $BQ = 333k$, applying Pythagoras to $\triangle BQC$ yields $QC = 333\sqrt{1-k^2}$. We then proceed using similar triangles: $\angle BYQ = \angle BQC = 90^{\circ}$ and $\angle YBQ = \angle QBC$, so by AA similarity $YB = 333k^2$. Likewise, $\angle CWQ = \angle BQC = 90^{\circ}$ and $\angle WCQ = \angle QCB$, so by AA similarity $WC = 333(1 - k^2)$. Thus $WC + YB = 333$.
Adding our two equations for $WC$ and $YB$ gives $2WC = 75 + 333 = 408$. Therefore, the answer is $PQ = ZW = CD - 2WC = 650 - 408 = \boxed{242}$.
~Orange_Quail_9
This will be my first solution on AoPS. My apologies in advance for any errors.
Angle bisectors can be thought of as the locus of all points equidistant from the lines whose angle they bisect. It can thus be seen that $P$ is equidistant from  $AB, AD,$ and $CD$ and $Q$ is equidistant from  $AB, BC,$ and $CD.$ If we let the feet of the altitudes from $P$ to $AB, AD,$ and $CD$ be called $E, F,$ and $G$ respectively, we can say that $PE = PF = PG.$ Analogously, we let the feet of the altitudes from $Q$ to $AB, BC,$ and $CD$ be $H, I,$ and $J$ respectively. Thus, $QH = QI = QJ.$ Because $ABCD$ is an isosceles trapezoid, we can say that all of the altitudes are equal to each other.
By SA as well as SS congruence for right triangles, we find that triangles $AEP, AFP, BHQ,$ and $BIQ$ are congruent. Similarly, $DFP, DGP, CJQ,$ and $CIQ$ by the same reasoning. Additionally, $EH = GJ = PQ$ since $EHQP$ and $GJQP$ are congruent rectangles.
If we then let $x = AE = AF = BH = BI,$ let $y = CI = CJ = DG = DF,$ and let $z = EH = GJ = PQ,$ we can create the following system of equations with the given side length information:
\begin{align*} 2x + z &= 500, \\ 2y + z &= 650, \\ x + y &= 333. \end{align*}
Adding the first two equations, subtracting by twice the second, and dividing by $2$ yields $z = PQ = \boxed{242}.$
~regular
Extend line $PQ$ to meet $AD$ at $P'$ and $BC$ at $Q'$. The diagram looks like this:
[asy] /* Made by MRENTHUSIASM */ size(300); pair A, B, C, D, A1, B1, C1, D1, P, Q, P1, Q1; A = (-250,6*sqrt(731)); B = (250,6*sqrt(731)); C = (325,-6*sqrt(731)); D = (-325,-6*sqrt(731)); A1 = bisectorpoint(B,A,D); B1 = bisectorpoint(A,B,C); C1 = bisectorpoint(B,C,D); D1 = bisectorpoint(A,D,C); P = intersectionpoint(A--300*(A1-A)+A,D--300*(D1-D)+D); Q = intersectionpoint(B--300*(B1-B)+B,C--300*(C1-C)+C); P1 = intersectionpoint(A--D,P--(-300)*(Q-P)+P); Q1 = intersectionpoint(B--C,Q--300*(Q-P)+Q); draw(anglemark(P,A,B,1000),red); draw(anglemark(D,A,P,1000),red); draw(anglemark(A,B,Q,1000),red); draw(anglemark(Q,B,C,1000),red); draw(anglemark(P,D,A,1000),red); draw(anglemark(C,D,P,1000),red); draw(anglemark(Q,C,D,1000),red); draw(anglemark(B,C,Q,1000),red); add(pathticks(anglemark(P,A,B,1000), n = 1, r = 0.15, s = 750, red)); add(pathticks(anglemark(D,A,P,1000), n = 1, r = 0.15, s = 750, red)); add(pathticks(anglemark(A,B,Q,1000), n = 1, r = 0.15, s = 750, red)); add(pathticks(anglemark(Q,B,C,1000), n = 1, r = 0.15, s = 750, red)); add(pathticks(anglemark(P,D,A,1000), n = 2, r = 0.12, spacing = 150, s = 750, red)); add(pathticks(anglemark(C,D,P,1000), n = 2, r = 0.12, spacing = 150, s = 750, red)); add(pathticks(anglemark(Q,C,D,1000), n = 2, r = 0.12, spacing = 150, s = 750, red)); add(pathticks(anglemark(B,C,Q,1000), n = 2, r = 0.12, spacing = 150, s = 750, red)); dot("$A$",A,1.5*dir(A),linewidth(4)); dot("$B$",B,1.5*dir(B),linewidth(4)); dot("$C$",C,1.5*dir(C),linewidth(4)); dot("$D$",D,1.5*dir(D),linewidth(4)); dot("$P$",P,1.5*NE,linewidth(4)); dot("$Q$",Q,1.5*NW,linewidth(4)); dot("$P'$",P1,1.5*W,linewidth(4)); dot("$Q'$",Q1,1.5*E,linewidth(4)); draw(A--B--C--D--cycle^^A--P--D^^B--Q--C^^P--Q); draw(P--P1^^Q--Q1,dashed); [/asy]
Since $\angle A + \angle D=\angle B + \angle C = 180^{\circ}$, it follows that $\angle P'AP+\angle P'DP = \angle Q'BQ + \angle Q'CQ = 90^{\circ}$. Thus, $\angle APD = \angle BQC = 90^{\circ}$, implying that $\triangle APD$ and $\triangle BQC$ are right triangles. Since $P'P$ and $Q'Q$ are medians, $P'P+Q'Q=\frac{333\times2}{2}=333$. Since $P'Q'=\frac{500+650}{2}=575$, we have $PQ+P'P+Q'Q=575$, or $PQ=575-333=\boxed{242}$.
~sigma
Let $PQ = x$. Note that since $AP$ bisects $\angle{A}$ and $DP$ bisects $\angle{D}$, we have \[\angle{APD} = 180^{\circ}-\tfrac12 \angle{A}-\tfrac12 \angle{D}=90^{\circ}.\] Let $\angle{ADP}=\theta$. We have that $\angle{ADC} = 2\theta.$ Now, drop an altitude from $A$ to $CD$ at $E$. Notice that $DE=\tfrac{650-500}{2}=75$. By the definition of cosine, we have \[\cos{2\theta}=1-2\cos^2{\theta}=\tfrac{75}{333}=\tfrac{25}{111} \implies \cos{\theta}=\tfrac{2\sqrt{1887}}{111}.\] Notice, however, that we can also apply this to $\triangle{APD}$; we have \[\cos{\theta}=\tfrac{DP}{333} \implies DP=6\sqrt{1887}.\] By the Pythagorean Theorem, we get \[AP=\sqrt{333^2-(6\sqrt{1887})^2}=3\sqrt{4773}.\] Then, drop an altitude from $P$ to $AB$ at $F$; if $AF=y$, then $PQ=x=500-2y$. Because $AP$ is an angle bisector, we see that $\angle{BAP}=\angle{DAP}=90^{\circ}-\theta$. Again, by the definition of cosine, we have \[\cos{(90^{\circ}-\theta)}=\sin{\theta}=\tfrac{\sqrt{4773}}{111}=\tfrac{y}{3\sqrt{4773}} \implies y=129.\] Finally, $PQ=500-2y=\boxed{242}$.
~pqr.
As in solution 4, $\angle APD = 90^{\circ}$. Set $k = AX$ and $x = DP$.
We know that $DZ = AX + \frac{DC-AB}{2}$, so $DZ = k + \frac{650-500}{2} = k + 75$.
$\triangle DPZ \sim \triangle APD$ by AA, so we have $\frac{PD}{AD} = \frac{ZD}{PD}$, resulting in
\[\frac{x}{333} = \frac{k+75}{x} \text{ (1)}\]
$\triangle APX \sim \triangle ADP$ by AA, so we have $\frac{AP}{AD} = \frac{AX}{AP}$, resulting in
\[\frac{\sqrt{333^2-x^2}}{333} = \frac{k}{\sqrt{333^2-k^2}} \text{ (2)}\]
From $\text{(1)}$, we have $x^2 = 333k + 333(75) = 333k + 24975$. From $\text{(2)}$, we have $333^2 - x^2 = 333k$, or $x^2 = 333^2 - 333k$. Thus, $333k + 24975 = 333^2 - 333k$. Solving for $k$ yields $k = 129$.
By symmetry, $YB = AX = 129$. Thus, $PQ = XY = AB - 2AX = 500 - 2(129) = \boxed{242}$.
~ adam_zheng


Answer:
242

### Let's define the program: A simple `dspy.ChainOfThought`

In [27]:
class GenerateResponse(dspy.Signature):
    """Solve the problem and provide the answer in the correct format."""
    problem = dspy.InputField()
    answer = dspy.OutputField()


program = dspy.ChainOfThought(GenerateResponse)

### Defining the evaluation metric
We simply check exact match between the predicted answer and the correct answer.

In [28]:
def metric(example, prediction, trace=None, pred_name=None, pred_trace=None):
    correct_answer = int(example['answer'])
    try:
        llm_answer = int(prediction.answer)
    except ValueError:
        return 0
    return int(correct_answer == llm_answer)

### Evaluating unoptimized Chain Of Thought

We evaluate with the thread budget defined above and tolerate up to `len(test_set)` transient errors so the run completes even on constrained proxies. If your provider enforces stricter limits, lower `n_threads` or tighten `max_errors`.

In [29]:
# Removed max_errors configuration since there should be no errors
eval_kwargs = dict(
    num_threads=n_threads,
    display_progress=True,
    display_table=5,
    provide_traceback=False,
)

evaluate = dspy.Evaluate(
    devset=test_set,
    metric=metric,
    **eval_kwargs,
)

baseline_result = evaluate(program)
baseline_result.score

Average Metric: 80.00 / 150 (53.3%): 100%|██████████| 150/150 [00:04<00:00, 36.92it/s]

2025/10/14 01:11:06 INFO dspy.evaluate.evaluate: Average Metric: 80 / 150 (53.3%)

,problem,example_answer,reasoning,pred_answer,metric
0,Find the sum of all integer bases $b>9$ for which $17_b$ is a divi...,70,We interpret 17_b = b+7 and 97_b = 9b+7. We need b+7 to divide 9b+...,70,✔️ [1]
1,"On $\triangle ABC$ points $A, D, E$, and $B$ lie in that order on ...",588,"Set up affine coordinates with A=(0,0), B=(1,0), C=(0,1). Points o...",441,✔️ [0]
2,The 9 members of a baseball team went to an ice-cream parlor after...,16,"We must count assignments of 3 labeled flavors (C, V, S) to 9 dist...",16,✔️ [1]
3,"Find the number of ordered pairs $(x,y)$, where both $x$ and $y$ a...",117,"We need integer solutions (x,y) in [-100,100] satisfying 12x^2 - x...",117,✔️ [1]
4,There are $8!= 40320$ eight-digit positive integers that use each ...,279,Divisibility by 22 means divisible by 2 and 11. Units digit must b...,279,✔️ [1]

53.33

[Trace(trace_id=tr-f6dbb5a338ef9090bfcc56af0e8a85ed), Trace(trace_id=tr-92f6f2b5eac55de5442284d2ce86865a), Trace(trace_id=tr-72d65b81bf1cb4ff8b118bb380af28a4), Trace(trace_id=tr-0a798dca3ef152ab1b522b223ff58ab0), Trace(trace_id=tr-5d8b846b95e291d61c55bf03234cce4c), Trace(trace_id=tr-15c0aaf9ea9547552879c7245b550547), Trace(trace_id=tr-01752f5cdc4a3702c40f17318e0363c9), Trace(trace_id=tr-25fc4a1a4990f1f665757b52894565d6), Trace(trace_id=tr-0703572354e9c59a9fc62cc952a0d1bb), Trace(trace_id=tr-183f81085a06a51104b764f8e13296e8)]

### Augmenting the metric for APEX
APEX benefits from feedback about why predictions fail. We extend the metric to provide textual guidance (and optional worked solutions) that the optimizer can feed into its failure and success analyses.

In [30]:
def metric_with_feedback(example, prediction, trace=None, pred_name=None, pred_trace=None):
    correct_answer = int(example['answer'])
    written_solution = example.get('solution', '')
    try:
        llm_answer = int(prediction.answer)
    except ValueError:
        feedback_text = (
            f"The final answer must be a valid integer and nothing else. You responded with '{prediction.answer}', which couldn't be parsed as an integer."
        )
        feedback_text += f" The correct answer is '{correct_answer}'."
        if written_solution:
            feedback_text += (
                f" Here's the full step-by-step solution:\n{written_solution}\n\n"
                "Reflect on this solution and ensure your final answer is a valid integer when you attempt similar problems."
            )
        return dspy.Prediction(score=0, feedback=feedback_text)

    score = int(correct_answer == llm_answer)
    if score == 1:
        feedback_text = f"Your answer is correct. The correct answer is '{correct_answer}'."
    else:
        feedback_text = f"Your answer is incorrect. The correct answer is '{correct_answer}'."

    if written_solution:
        feedback_text += (
            f" Here's the full step-by-step solution:\n{written_solution}\n\n"
            "Use it to identify the mistakes in your reasoning before trying again."
        )

    return dspy.Prediction(score=score, feedback=feedback_text)

### Optimize the program with `dspy.APEX`

APEX runs targeted analyses over failure and success cases, proposes hypotheses with complete prompt updates, and keeps the best candidate on the calibration set. We limit the budget to a few iterations to keep the tutorial runtime manageable. Use `verbosity` to control logging (`"none"`, `"normal"`, or `"high"`) and `num_threads` to parallelize execution.

In [31]:
from dspy.teleprompt.apex_optimizer import APEX

# Fixed configuration for parallel execution with enhanced visibility
optimizer = APEX(
    metric=metric_with_feedback,
    analysis_lm=analysis_lm,        # Required parameter
    hypothesis_lm=analysis_lm,       # Optional, defaults to analysis_lm if not provided
    analysis_adapter=analysis_adapter,
    hypothesis_adapter=hypothesis_adapter,
    max_iterations=50,
    num_hypotheses=1,
    num_eval_runs=1,
    train_sample=20,
    success_threshold=1.0,
    convergence_patience=5,
    num_threads=n_threads,           # Using n_threads=50 from configuration
    verbosity="high",                # Enhanced visibility into the optimization process
    seed=42,
)

optimized_program = optimizer.compile(
    student=program,
    trainset=train_set,
    valset=val_set,
)

2025/10/14 01:11:06 INFO dspy.teleprompt.apex_optimizer: APEX: running with num_threads=50
2025/10/14 01:11:06 INFO dspy.teleprompt.apex_optimizer: APEX: Configuration - max_iterations=50, num_hypotheses=1, success_threshold=1.00, convergence_patience=5
2025/10/14 01:11:06 INFO dspy.teleprompt.apex_optimizer: APEX: Using seed=42 for reproducibility
2025/10/14 01:11:06 INFO dspy.teleprompt.apex_optimizer: APEX: Evaluating initial baseline on validation set

Processed 45 / 45 examples: 100%|██████████| 45/45 [00:00<00:00, 428.60it/s]

2025/10/14 01:11:06 INFO dspy.teleprompt.apex_optimizer: APEX: Initial baseline score=0.5111
2025/10/14 01:11:06 INFO dspy.teleprompt.apex_optimizer: APEX: iteration 1 started (train sample=20, val size=45)
2025/10/14 01:11:06 INFO dspy.teleprompt.apex_optimizer: APEX: Sampled 20 training examples from 45 total

Processed 20 / 20 examples: 100%|██████████| 20/20 [00:00<00:00, 101.36it/s]

2025/10/14 01:11:06 INFO dspy.teleprompt.apex_optimizer: APEX: Train evaluation complete - 6 failures, 14 successes

Processed 1 / 6 examples:  17%|█▋        | 1/6 [00:22<01:51, 22.39s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "ro...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Processed 6 / 6 examples: 100%|██████████| 6/6 [00:32<00:00,  5.40s/it]

2025/10/14 01:11:39 INFO dspy.teleprompt.apex_optimizer: APEX: failure analysis #1 (ambiguous-instruction) → In unknown (Predict), the model produced an incorrect final answer '13' for the AIME problem requiring m+n=33. Execution_flow shows a single-step solver with reasoning that abandoned the structured trig/substitution approach and instead guessed, leading to a wrong result despite the metric_feedback detailing the correct derivation to (1-x)(1-y)(1-z))^2 = 1/32 → m+n=33.
2025/10/14 01:11:39 INFO dspy.teleprompt.apex_optimizer: APEX: failure analysis #2 (ambiguous-instruction) → In unknown (Predict), the counting step subtracted 48 invalid pairs instead of the correct 3 after excluding a=6 and a/b=20. The execution flow shows the model excluded a=6 and any 20 (yielding 231), then removed (12,21) and (16,28) correctly but also incorrectly subtracted all cases with a=6 (double-counted) and both a=20 and b=20 (over-subtraction), arriving at 227 instead of 228.
2025/10/14 01:11:39 INFO dspy.teleprompt.apex_optimizer: APEX: failure analysis #3 (missing-constraint) → In unknown (Predict), the final bounded-region count subtracted the wrong number of unbounded faces. Using Euler’s formula they computed F = 2 + mn + I = 247, then incorrectly concluded bounded regions = 241, whereas the correct derivations (and metric feedback) show bounded regions = C(m,2)C(n,2) + mn − 1 = 210 + 35 − 1 = 244. The misstep is an incorrect outer-face adjustment after computing total faces.
2025/10/14 01:11:39 INFO dspy.teleprompt.apex_optimizer: APEX: failure analysis #4 (ambiguous-instruction) → In unknown (Predict), the solver misinterpreted the counting task as counting inscribed rectangles determined by antipodal vertex pairs on a 24-gon, yielding 30, instead of counting all axis/diagonal-aligned rectangles in a regular dodecagon as required by the problem input. Execution flow shows Actual inputs used a different problem (24-gon perfect matchings), and Actual outputs gave answer 113 with reasoning unrelated to rectangles in a 12-gon.
2025/10/14 01:11:39 INFO dspy.teleprompt.apex_optimizer: APEX: failure analysis #5 (ambiguous-instruction) → In unknown (Predict), the model produced an incorrect final answer '117' without following the geometric solution constraints. Execution flow shows this predictor received the circle geometry problem but returned an unrelated guessed value; metric_feedback indicates the correct area computation leads to 18√15 and final m+n=33, whereas the model output '117' (likely a misplaced memory guess) contradicts the provided step-by-step derivation.
2025/10/14 01:11:39 INFO dspy.teleprompt.apex_optimizer: APEX: failure analysis #6 (wrong-value) → In unknown (Predict), the final answer was given as '100' while the metric_feedback shows the correct side length is 80, with a clear proportional-similarity derivation: (5/4)x + x + (3/2)x = 300 -> x = 80. The predictor produced an incorrect numeric result contrary to the provided geometric similarity relations.

Processed 1 / 6 examples:  17%|█▋        | 1/6 [00:22<01:52, 22.58s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "su...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Processed 6 / 6 examples: 100%|██████████| 6/6 [00:31<00:00,  5.19s/it]

2025/10/14 01:12:10 INFO dspy.teleprompt.apex_optimizer: APEX: success analysis #1 (clear-instruction-execution) → The predictor derived the volume ratio by modeling edges with equal length, using rhombus diagonal relations to fix dot products, forming the Gram matrix for edge vectors, and comparing determinants for the two sign configurations to get the ratio 63/62.
2025/10/14 01:12:10 INFO dspy.teleprompt.apex_optimizer: APEX: success analysis #2 (clear-instruction-execution) → The solver enumerated semifinal pairings and computed Carl’s tournament win probability by conditioning on matchups and using given independent match probabilities, then averaged over equally likely brackets.
2025/10/14 01:12:10 INFO dspy.teleprompt.apex_optimizer: APEX: success analysis #3 (clear-instruction-execution) → The predictor transformed the symmetric cubic sum into symmetric polynomials (p1, p2, p3) using Newton’s identities and a centering shift (a,b,c) -> (100−x,100−y,100−z), deriving the invariant xyz=0; this forced one variable to equal 100, enabling complete enumeration under a+b+c=300.
2025/10/14 01:12:10 INFO dspy.teleprompt.apex_optimizer: APEX: success analysis #4 (clear-instruction-execution) → The solver recognized that any decimal-below-1000 palindrome that is also an octal palindrome must correspond to an octal 4-digit palindrome of the form 1BB1_8 and enumerated its decimal values, identifying 585 as both decimal-palindromic and within range, thus the maximum.
2025/10/14 01:12:10 INFO dspy.teleprompt.apex_optimizer: APEX: success analysis #5 (clear-instruction-execution) → The solver maximized x_{76} and minimized x_{16} by concentrating all positive mass on indices 76–100 and all negative mass on indices 1–16, with zeros in between, using the fixed sums |negatives|=|positives|=1/2 to derive x_{76}=1/50 and x_{16}=-1/32.
2025/10/14 01:12:10 INFO dspy.teleprompt.apex_optimizer: APEX: success analysis #6 (clear-instruction-execution) → The solver leveraged symmetry in an isosceles trapezoid to place P and Q on a line parallel to the bases and used consistent angle-bisector/altitude relations to reduce PQ to midline minus symmetric offsets, yielding PQ = 575 − 333 = 242.
2025/10/14 01:12:10 INFO dspy.teleprompt.apex_optimizer: APEX: iteration 1 analyzed 6 failure(s) and 6 success(es)
2025/10/14 01:12:10 INFO dspy.teleprompt.apex_optimizer: APEX: Generating up to 1 hypotheses from 6 failures

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='{\n  "hy...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(
2025/10/14 01:12:38 INFO dspy.teleprompt.apex_optimizer: APEX: hypothesis #1 (Introduce a minimal but comprehensive structured solution rubric within a single-predictor prompt: restate the task, plan steps, execute with labeled equations, track inclusions/exclusions explicitly, perform a final verification/sanity check (including outer-face vs bounded-region distinctions), and output only the final numeric in the required format. This preserves successful reasoning while preventing guessing and task drift.) targeting Ambiguous instruction leading to guessing instead of step-by-step derivation, Missing explicit requirements for verification and final check (outer face/bounded regions adjustment), Lack of constraints on staying on-task and restating the problem to prevent drift, No requirement to preserve and tally exclusions exactly once (avoid double-counting), No explicit final-unit/format and sanity-check step [impact=0.82, generalizability=0.86]
2025/10/14 01:12:38 INFO dspy.teleprompt.apex_optimizer:   → predict: You are a careful competition-math solver. Solve the problem with structured reasoning, then output ONLY the final answer in the required format.

Instructions:
1) Restate the task precisely in your o...
2025/10/14 01:12:38 INFO dspy.teleprompt.apex_optimizer:      Rationale: Adds a structured rubric without changing mathematical freedom: restatement prevents task drift, planning reduces mid-solution guessing, explicit inclusion/exclusion tracking targets double-count/over-subtraction errors, and the bounded vs. total faces note addresses the outer-face adjustment mistake. A verification step catches arithmetic slips leading to wrong numeric finals. Final-output constraint preserves correct format and successful behaviors observed.
2025/10/14 01:12:38 INFO dspy.teleprompt.apex_optimizer: APEX: iteration 1 produced 1 hypothesis(es)
2025/10/14 01:12:38 INFO dspy.teleprompt.apex_optimizer: APEX: hypothesis #1 - strategy: Introduce a minimal but comprehensive structured solution rubric within a single-predictor prompt: restate the task, plan steps, execute with labeled equations, track inclusions/exclusions explicitly, perform a final verification/sanity check (including outer-face vs bounded-region distinctions), and output only the final numeric in the required format. This preserves successful reasoning while preventing guessing and task drift., impact: 0.82, updating: predict
2025/10/14 01:12:38 INFO dspy.teleprompt.apex_optimizer: APEX: Detailed hypothesis info follows...

Processed 45 / 45 examples: 100%|██████████| 45/45 [00:00<00:00, 1011.03it/s]

2025/10/14 01:12:38 INFO dspy.teleprompt.apex_optimizer: APEX: iteration 1 baseline score=0.5111

Processed 1 / 45 examples:   2%|▏         | 1/45 [00:08<06:08,  8.38s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Processed 3 / 45 examples:   4%|▍         | 2/45 [00:08<02:37,  3.67s/it]

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content='[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

Processed 45 / 45 examples: 100%|██████████| 45/45 [01:53<00:00,  2.51s/it]

2025/10/14 01:14:31 INFO dspy.teleprompt.apex_optimizer: APEX: iteration 1 hypothesis score=0.5778
2025/10/14 01:14:31 INFO dspy.teleprompt.apex_optimizer: APEX: hypothesis details → {'observation': 'Failures cluster around ambiguous or underspecified instructions causing the solver to guess, switch tasks, or mishandle final adjustments. Specific patterns: (1) abandoning structured derivations for a guess, (2) miscount due to double-subtraction/over-subtraction, (3) incorrect outer-face/bounded-region adjustment, (4) task drift to a different polygon/problem, and (5) wrong numeric final despite correct relations. Successes show the model can execute multi-step, structured math when instructions are clear.', 'fixable_root_causes': ['Ambiguous instruction leading to guessing instead of step-by-step derivation', 'Missing explicit requirements for verification and final check (outer face/bounded regions adjustment)', 'Lack of constraints on staying on-task and restating the problem to prevent drift', 'No requirement to preserve and tally exclusions exactly once (avoid double-counting)', 'No explicit final-unit/format and sanity-check step'], 'non_fixable_root_causes': [], 'impact_score': 0.82, 'generalizability_score': 0.86, 'strategy': 'Introduce a minimal but comprehensive structured solution rubric within a single-predictor prompt: restate the task, plan steps, execute with labeled equations, track inclusions/exclusions explicitly, perform a final verification/sanity check (including outer-face vs bounded-region distinctions), and output only the final numeric in the required format. This preserves successful reasoning while preventing guessing and task drift.', 'expected_impact': 'Reduce wrong-value and ambiguous-instruction errors by enforcing stepwise reasoning and final verification. Specifically: cut guessing-related wrong finals by ~60%, eliminate most task-drift cases, and fix outer-face/bounded-region adjustment mistakes in ~50% of relevant cases. Overall expected accuracy improvement: 10–20% on the sampled failure categories.', 'prompt_changes': {'predict': {'new_prompt': 'You are a careful competition-math solver. Solve the problem with structured reasoning, then output ONLY the final answer in the required format.\n\nInstructions:\n1) Restate the task precisely in your own words (one sentence) to lock the target. Identify what quantity and format are required (e.g., integer, m+n, etc.).\n2) Plan the solution in 2–4 bullet points before calculating (methods: algebra, counting with cases, geometry relations, invariant/symmetry, etc.).\n3) Execute step-by-step. Use labeled equations and maintain exact values (fractions, radicals) until the end. For counting problems, explicitly track inclusions/exclusions and ensure each exclusion is applied exactly once. For planar graphs/arrangements, distinguish total faces vs. bounded regions and adjust for the outer face explicitly.\n4) Verification:\n   - Sanity-check units, domains, and boundary cases.\n   - If using formulas like Euler’s or combinatorial coefficients, verify with a small analogous example.\n   - Recompute the final step independently (quick check) to catch arithmetic slips.\n5) Final output formatting:\n   - Provide ONLY the final answer exactly as requested by the problem (e.g., a single integer, or m+n as a single integer). No extra text.\n\nConstraints:\n- Do not guess. If multiple paths exist, choose one and carry it through consistently.\n- Stay on the exact problem. Do not switch to a different polygon, number of sides, or unrelated task.\n- Keep intermediate reasoning concise but explicit enough to audit counts and adjustments.\n\nNow solve:\n[Problem Starts]\n{input}\n[Problem Ends]\n\nAfter completing steps 1–4, output ONLY the final answer as specified in step 5.', 'rationale': 'Adds a structured rubric without changing mathematical freedom: restatement prevents task drift, planning reduces mid-solution guessing, explicit inclusion/exclusion tracking targets double-count/over-subtraction errors, and the bounded vs. total faces note addresses the outer-face adjustment mistake. A verification step catches arithmetic slips leading to wrong numeric finals. Final-output constraint preserves correct format and successful behaviors observed.', 'change_magnitude': <ChangeMagnitude.MODERATE: 'moderate'>}}}
2025/10/14 01:14:31 INFO dspy.teleprompt.apex_optimizer: APEX: New best candidate found with score 0.5778
2025/10/14 01:14:31 INFO dspy.teleprompt.apex_optimizer: APEX: Improved 1 predictor prompt(s) - strategy: Introduce a minimal but comprehensive structured solution rubric within a single-predictor prompt: restate the task, plan steps, execute with labeled equations, track inclusions/exclusions explicitly, perform a final verification/sanity check (including outer-face vs bounded-region distinctions), and output only the final numeric in the required format. This preserves successful reasoning while preventing guessing and task drift.
2025/10/14 01:14:31 INFO dspy.teleprompt.apex_optimizer: APEX: Detailed improved prompts:
2025/10/14 01:14:31 INFO dspy.teleprompt.apex_optimizer:   → predict: You are a careful competition-math solver. Solve the problem with structured reasoning, then output ONLY the final answer in the required format.

Instructions:
1) Restate the task precisely in your own words (one sentence) to lock the target. Identify what quantity and format are required (e.g., in...
2025/10/14 01:14:31 INFO dspy.teleprompt.apex_optimizer: APEX: iteration 1 best score=0.5778
2025/10/14 01:14:31 INFO dspy.teleprompt.apex_optimizer: APEX: Score improvements from baseline: [0.06666666666666665]
2025/10/14 01:14:31 INFO dspy.teleprompt.apex_optimizer: APEX: Updating program with hypothesis improvements
2025/10/14 01:14:31 INFO dspy.teleprompt.apex_optimizer: APEX: iteration 2 started (train sample=20, val size=45)
2025/10/14 01:14:31 INFO dspy.teleprompt.apex_optimizer: APEX: Sampled 20 training examples from 45 total

Processed 20 / 20 examples: 100%|██████████| 20/20 [01:00<00:00,  3.02s/it]

2025/10/14 01:15:31 INFO dspy.teleprompt.apex_optimizer: APEX: Train evaluation complete - 12 failures, 8 successes

  0%|          | 0/12 [00:00<?, ?it/s]

2025/10/14 01:19:52 WARNING dspy.utils.parallelizer: SIGINT received. Cancelling.
2025/10/14 01:19:52 INFO dspy.teleprompt.apex_optimizer: APEX: Optimization interrupted by user (Ctrl+C)

  0%|          | 0/12 [04:20<?, ?it/s]

2025/10/14 01:19:52 INFO dspy.teleprompt.apex_optimizer: APEX: Optimization complete - stopped after 2 iterations (interrupted)
2025/10/14 01:19:52 INFO dspy.teleprompt.apex_optimizer: APEX: Final score: 0.5778 (initial baseline: 0.5111)
2025/10/14 01:19:52 INFO dspy.teleprompt.apex_optimizer: APEX: Summary - evaluated 4 candidates from 2 hypotheses
2025/10/14 01:19:52 INFO dspy.teleprompt.apex_optimizer: APEX: Best score trajectory across iterations: [0.5777777777777777, 0.5777777777777777]

[Trace(trace_id=tr-6c054826c060aa5220de985d6a85d117), Trace(trace_id=tr-8cd8094af47b1c058bb1411ef4f220bd), Trace(trace_id=tr-f569752c8c6e2720c5195e40982ff5e9), Trace(trace_id=tr-d96e1c6106b221db2c645cc913ffd01d), Trace(trace_id=tr-dadf650acca0c4897ab1cfab0c5161ff), Trace(trace_id=tr-a0708b72564809384f1a504253583a33), Trace(trace_id=tr-ba992545821ae7397d247e7fa446f439), Trace(trace_id=tr-9b4f0f780a4d48d44de20ff1a7feca36), Trace(trace_id=tr-6713afeeb22593125b7ff6c83cc6a3e8), Trace(trace_id=tr-7f8a9bb91e10a228268d42d525157711)]

### Inspect the APEX-optimized prompt

In [ ]:
print(optimized_program.predict.signature.instructions)

You are a careful competition-math solver. Solve the problem with rigorous, explicit reasoning and a final answer in the required format.

Follow this structure exactly:
1) Plan: Briefly restate the goal and outline the method (key identities/constraints to use).
2) Derive: Carry out the computation step by step. Show key intermediate quantities and formulas used.
3) Check: Validate your result by addressing all that apply:
   - Constraints: Verify assumptions match the problem (e.g., for geometry: similarity/cyclicity/collinearity/angle or power-of-a-point conditions; for counting/regions: Euler/V-E+F, unbounded vs bounded counts; for sequences: arithmetic progression conditions and edge cases).
   - Edge cases: Enumerate and confirm no missing or double-counted cases (e.g., forbidden APs like 3,5,7,9; cross-endpoint cases; boundary pairs).
   - Alternative sanity check: Plug back into definitions or a second quick method to spot inconsistencies.
4) Conclude: State the final answer in the required format only.

Formatting rules:
- Show your reasoning in steps 1–3 succinctly but completely. Avoid hand-wavy guesses.
- If the problem is AIME-style, the final line must be a 3-digit number with leading zeros if needed (e.g., 033). Otherwise, output the exact value requested.
- Do not output multiple different final answers.

Now solve the problem:
[Problem]: {{problem_text}}

### Evaluating the Chain Of Thought optimized with APEX

In [ ]:
evaluate(optimized_program)

Average Metric: 89.00 / 150 (59.3%): : 151it [02:41,  1.07s/it]

2025/10/12 00:07:35 INFO dspy.evaluate.evaluate: Average Metric: 89 / 150 (59.3%)

,problem,example_answer,reasoning,pred_answer,metric
0,Find the sum of all integer bases $b>9$ for which $17_b$ is a divi...,70,Plan: We are asked to find all integer bases b>9 such that the bas...,70,✔️ [1]
1,"On $\triangle ABC$ points $A, D, E$, and $B$ lie in that order on ...",588,Plan: We are given triangle ABC with collinear points on AB: A-D-E...,576,✔️ [0]
2,The 9 members of a baseball team went to an ice-cream parlor after...,16,Plan: We must count assignments of 9 distinct players to flavors C...,16,✔️ [1]
3,"Find the number of ordered pairs $(x,y)$, where both $x$ and $y$ a...",117,"1) Plan: We need integer solutions (x,y) with -100 ≤ x,y ≤ 100 to ...",117,✔️ [1]
4,There are $8!= 40320$ eight-digit positive integers that use each ...,279,Plan: We must count 8-digit permutations of digits 1..8 divisible ...,279,✔️ [1]

EvaluationResult(score=59.33, results=<list of 150 results>)

/Users/aviram.kofman/Documents/Projects/dspy/.venv/lib/python3.10/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected 9 fields but got 6: Expected `Message` - serialized value may not be as expected [input_value=Message(content="[[ ## re...: None}, annotations=[]), input_type=Message])
  PydanticSerializationUnexpectedValue(Expected `StreamingChoices` - serialized value may not be as expected [input_value=Choices(finish_reason='st...ider_specific_fields={}), input_type=Choices])
  return self.__pydantic_serializer__.to_python(

APEX typically improves the GPT-4.1 Mini's performance on AIME 2025 by leveraging targeted analyses while keeping the overall evaluation flow identical to the GEPA tutorial.